server:
    contextPath: /ufgovPlus
    port: 8081
    session:
        timeout: -1

spring:
    datasource:
        name: ysxx
        url: jdbc:sqlserver://10.60.1.37:1433;databaseName=ysxx
        username: sa
        password: Abc123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp

logging:
    level:
      com.enterprise: DEBUG
      org.springframework.web: INFO